const assert=require('node:assert/strict');
const R=require('../results.js'),round=require('./fixtures/v1-round.json'),holes=round.holes;
const instruction='Analyze this round as my golf coach. Identify the biggest scoring patterns, strengths, mistakes, course-management issues, and likely opportunities to lower my handicap. Use my notes and hole-level results as context. Give me specific coaching feedback and prioritize what I should work on in my next practice session.';
const partial={1:{score:5,tee:'Left',gir:false,putts:3,penalties:1,note:'Pushed right & <trees>\nRecovered safely.'},5:{score:3,tee:'Fairway',gir:true,putts:2},10:{putts:0,penalties:0}};
const report=R.coachReport(round,partial);
for(const value of ['Round status: In Progress','Holes completed (score recorded): 2/18','Score for completed holes: 8','Relative to par for completed holes: +1','Front nine: 8 (2/9 holes) | Back nine: —','Fairways hit / eligible fairways: 0/14 (1 tee results recorded)','GIR: 1/18 (2 results recorded)','Total putts: 5 (3 holes recorded)','Penalty strokes: 1 (2 holes recorded)','Hole 5 | Par 3 | 124 yd | Score 3 | Tee N/A','  Note: Pushed right & <trees>\n  Recovered safely.'])assert.ok(report.includes(value),value);
assert.ok(report.endsWith(instruction));assert.equal((report.match(/^Hole \d+ \|/gm)||[]).length,18);
const clean=R.clean(partial,holes),s=R.stats(holes,clean);
assert.ok(report.includes('Relative to par for completed holes: '+R.relativeLabel(s)));
assert.ok(report.includes('Front nine: '+R.totalLabel(holes.slice(0,9),clean)));
const empty=R.coachReport(round,{});
assert.ok(empty.includes('Score for completed holes: —'));assert.ok(empty.includes('Relative to par for completed holes: —'));
assert.ok(empty.includes('Total putts: 0 (0 holes recorded)'));
const full=Object.fromEntries(holes.map(h=>[h.n,{score:h.par,putts:2,penalties:0,gir:true,tee:'Fairway'}]));
const complete=R.coachReport(round,full);
assert.ok(complete.includes('Round status: Complete'));assert.ok(complete.includes('Holes completed (score recorded): 18/18'));
assert.ok(complete.includes('Score for completed holes: 72'));assert.ok(complete.includes('Relative to par for completed holes: E'));
assert.ok(complete.includes('Front nine: 36 | Back nine: 36'));assert.ok(complete.includes('Fairways hit / eligible fairways: 14/14'));
assert.equal((complete.match(/^Hole \d+ \|/gm)||[]).length,18);
assert.equal(R.activeHole(holes,{},undefined),1);
assert.equal(R.activeHole(holes,{8:{score:4},14:{}},undefined),8);
assert.equal(R.activeHole(holes,{8:{score:4}},99),8);
assert.equal(R.activeHole(holes,{8:{score:4}},9),9);
assert.equal(R.afterEntry(holes,8,14,{},{}),8);
assert.equal(R.afterEntry(holes,8,1,{score:4},{score:5}),8);
assert.equal(R.afterEntry(holes,8,14,{}, {tee:'Left'}),14);
assert.equal(R.afterEntry(holes,8,14,{score:4},{score:5}),8);
assert.equal(R.afterAdvance(holes,{8:{score:4}},8,8),9);
assert.equal(R.afterAdvance(holes,{},8,8),8);
assert.equal(R.afterAdvance(holes,{14:{score:5}},8,14),8);
assert.equal(R.afterAdvance(holes,{18:{score:5}},18,18),18);
console.log('Coach export and active-hole state tests passed');
